apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    app: haproxy
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: httpingress
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
    name: httpsingress
