apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-api-ingress
  namespace: default
spec:
  rules:
    - host: openapi.kubernetes.local
      http:
        paths:
          - path: /openapi/v2
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  number: 443
