apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moodle-operator-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: moodles.moodlecontroller.kubeplus
  # annotations:
  #   composition: Deployment, Service, PersistentVolume, PersistentVolumeClaim
spec:
  group: moodlecontroller.kubeplus
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:


          spec:
            type: object
            properties:
              mySQLServiceName:
                type: string
              mySQLUserName:
                type: string
              mySQLUserPassword:
                type: string
              moodleAdminEmail:
                type: string
              pvcVolumeName:
                type: string
              domainName:
                type: string
              tls:
                type: string
          status:
            type: object
            properties:
              podName:
                type: string
              secretName:
                type: string
              status:
                type: string
              url:
                type: string
  names:
    kind: Moodle
    singular: moodle
    plural: moodles
  scope: Namespaced
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: moodle-operator-deployment
#   labels:
#     app: moodle-operator
# spec:
#   replicas: 1 
#   selector:
#     matchLabels:
#       app: moodle-operator
#   template:
#     metadata:
#       labels:
#         app: moodle-operator
#     spec:
#       containers:
#       - name: moodle-operator
#         image: moodle-operator:0.5.0
#         imagePullPolicy: Never
      #   volumeMounts:
      #   - mountPath: /testing
      #     name: example-volume
      # volumes:
      # - name: example-volume
      #   hostPath:
      #     path: /home/nadeko/test/
      #     type: Directory