apiVersion: v1
kind: Service
metadata:
  name: moodle2-mysql
  namespace: customer2
  labels:
    app: moodle2-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: moodle2-mysql
  type: ClusterIP
---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: moodle2-mysql-data
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/mysql-data"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle2-mysql-data
  namespace: customer2
  labels:
    app: moodle2-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle2-mysql
  namespace: customer2
  labels:
    app: moodle2-mysql
spec:
  selector:
    matchLabels:
      app: moodle2-mysql
  template:
    metadata:
      labels:
        app: moodle2-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password1
        - name: MYSQL_DATABASE
          value: moodle
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_PASSWORD
          value: password1
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command: ["/bin/sh", "-i", "-c", "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: moodle2-mysql-data
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
#   namespace: customer2
# type: Opaque
# data:
#   mysql-password: password1
# ---